PUT http://localhost:4000/patients/8d494fca-e62a-433c-ae5a-a755817bc808
Content-Type: application/json

{
  "name": "rahul",
  "address": "123 Main St, Springfield",
  "email": "harry@gmail.com",
  "dateOfBirth": "1990-01-01"


}
